apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka 
  namespace: astra-infra
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts/blob/main/bitnami/kafka/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
